name: RUN calculations

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to main branch
        uses: actions/checkout@v3.3.0
      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run main script
        run: python main.py
      - name: Commit and Push new CSV to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'

    # run: |
    #   git config --global user.email "actions@github.com"
    #   git config --global user.name "GitHub Actions"
    #   git add 1h.csv
    #   git commit -m "Update 1h.csv"
    #   git push origin main

    #     # - name: Cache dependencies and build outputs to improve workflow execution time.
    #     #   uses: actions/cache@v3
    #     #   with:
    #     #     path: node_modules
    #     #     key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
    #     # - name: Install dependencies
    #     #   run: npm install
    #     # - name: Generate README file
    #     #   run: node index.js
