name: RUN calculations

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to main branch
        uses: actions/checkout@v2
      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run download data from bybit
        run: python download_data_bybit.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_API_SECRET: ${{ secrets.TEST_API_SECRET }}
      - name: Run main script
        run: python main.py
      - name: Run bybit script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_API_SECRET: ${{ secrets.TEST_API_SECRET }}

        run: python exchange_actions.py

      - name: Commit and Push new CSV to the repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add 1h.csv 1h_bybit.csv
          git commit -m "Update 1h.csv"
          git push origin main
